---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
name: vic-os
description: Fedora COSMIC Atomic base + kernel-blu (COPR) + UBlue akmods (bazzite stream) + COSMIC/Wayland Flatpaks
base-image: quay.io/fedora-ostree-desktops/cosmic-atomic:fedora-42
image-version: latest

modules:
  - type: rpm-ostree
    repos:
      - https://copr.fedorainfracloud.org/coprs/sentry/kernel-blu/repo/fedora-%OS_VERSION%/sentry-kernel-blu-fedora-%OS_VERSION%.repo
    install:
      - kernel
      - kernel-core
      - kernel-modules
      - kernel-modules-extra

  - type: akmods
    base: bazzite
    install:
      - evdi
      - xone
      - v4l2loopback
      - openrazer
      - dualsense
    # nvidia-driver: nvidia-open
    # nvidia-driver: nvidia

  - type: rpm-ostree
    install:
      - gamemode
      - goverlay
      - mangohud
      - power-profiles-daemon

  - type: default-flatpaks
    system:
      install:
        - org.mozilla.Firefox
        - com.github.tchx84.Flatseal
        - md.obsidian.Obsidian
        - com.discordapp.Discord
        - org.gnome.Console
        - org.gnome.Calculator
        - org.gnome.FileRoller
        - org.gnome.TextEditor
        - org.videolan.VLC
        - com.github.wwmm.easyeffects
        - org.libreoffice.LibreOffice
        - org.gimp.GIMP

  - type: os-release
    properties:
      NAME: vic-os
      PRETTY_NAME: "vic‑os (COSMIC Atomic + kernel-blu + akmods)"
      VARIANT: "vic-os"
      VARIANT_ID: vic-os

  - type: signing
