---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
name: vic-os
description: Bazzite-based image with COSMIC Desktop instead of KDE Plasma
base-image: ghcr.io/ublue-os/bazzite
image-version: stable

modules:
  # Install COSMIC from COPR and remove KDE/SDDM
  - type: rpm-ostree
    repos:
      - https://copr.fedorainfracloud.org/coprs/ryanabx/cosmic-epoch/repo/fedora-%OS_VERSION%/ryanabx-cosmic-epoch-fedora-%OS_VERSION%.repo
    install:
      - @cosmic-desktop-environment
      - cosmic-greeter
      - cosmic-edit
      - cosmic-files
      - cosmic-player
      - cosmic-screenshot
      - cosmic-randr
    remove:
      - plasma-desktop
      - plasma-workspace
      - kde-workspace
      - kde-settings
      - sddm
      - sddm-breeze
      - kde-cli-tools
      - konsole
      - kwin
      - kscreenlocker

  # Set COSMIC greeter as the display manager
  - type: systemd
    system:
      enabled:
        - cosmic-greeter.service
      disabled:
        - sddm.service
      masked:
        - sddm.service

  # Flatpaks tailored for COSMIC/Wayland
  - type: default-flatpaks
    system:
      install:
        - org.mozilla.Firefox
        - com.github.tchx84.Flatseal
        - md.obsidian.Obsidian
        - com.discordapp.Discord
        - org.gnome.Console
        - org.gnome.Calculator
        - org.gnome.FileRoller
        - org.gnome.TextEditor
        - org.videolan.VLC
        - com.github.wwmm.easyeffects
        - org.libreoffice.LibreOffice
        - org.gimp.GIMP

  # Branding
  - type: os-release
    name: vic-os
    pretty-name: "vic‑os (Bazzite + COSMIC)"
    variant: "vic-os"
    variant-id: vic-os

  # Sign the image if cosign is configured
  - type: signing
